const $=id=>document.getElementById(id);const KEY='roseGardenCustomersV3';
const demo=[
{id:'demo1',name:'Jessica Wang',phone:'(315) 555-0123',gender:'女',features:'喜欢粉色、方圆形',tech:'Annie',notes:'指甲偏薄，轻轻打磨',tipPattern:'通常 $10',createdAt:'2026-07-20',visits:[{id:'v1',date:'2026-08-03',service:'Builder Gel Fill + French',tech:'Annie',amount:65,tip:10,notes:'裸粉色法式'}]},
{id:'demo2',name:'Emily Chen',phone:'(315) 555-0188',gender:'女',features:'短甲、喜欢自然色',tech:'Charlotte',notes:'怕磨，喜欢安静',tipPattern:'约 20%',createdAt:'2026-07-12',visits:[{id:'v2',date:'2026-07-26',service:'Gel Manicure',tech:'Charlotte',amount:35,tip:7,notes:'奶茶色'},{id:'v3',date:'2026-08-01',service:'Gel Manicure',tech:'Charlotte',amount:40,tip:8,notes:'加简单线条'}]},
{id:'demo3',name:'Sophie Liu',phone:'(315) 555-0196',gender:'女',features:'喜欢杏仁形',tech:'Mia',notes:'对气味敏感',tipPattern:'通常 $15',createdAt:'2026-07-18',visits:[]}
];
let customers=JSON.parse(localStorage.getItem(KEY)||'null')||demo;let activeId=null;let manage=false;
const save=()=>{localStorage.setItem(KEY,JSON.stringify(customers));renderAll()};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);const money=n=>`$${(Number(n)||0).toFixed(2)}`;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===id));closeDrawer();if(id==='add'&&!$('customerId').value)resetForm();if(id==='detail')renderDetail();scrollTo({top:0,behavior:'smooth'})}
function openDrawer(){$('drawer').classList.add('open');$('shade').classList.add('show')}function closeDrawer(){$('drawer').classList.remove('open');$('shade').classList.remove('show')}
function initials(n){return n.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'♡'}
function card(c){const v=c.visits||[];const latest=[...v].sort((a,b)=>b.date.localeCompare(a.date))[0];return `<article class="customer-card" data-view="${c.id}"><div class="avatar">${esc(initials(c.name))}</div><div class="customer-main"><div class="customer-top"><b>${esc(c.name)}</b><span class="badge">${v.length} 次</span></div><p>${esc(c.phone||'未填写电话')} · ${esc(c.features||'暂无特征')}</p><small>${latest?`最近：${esc(latest.service)}`:`常找：${esc(c.tech||'未填写')}`}</small></div><div class="card-actions"><button class="mini-btn" data-edit="${c.id}">编辑</button><button class="mini-btn danger" data-delete="${c.id}">删除</button></div><span class="chev">›</span></article>`}
function renderStats(){const visits=customers.flatMap(c=>c.visits||[]);const now=new Date();$('statCustomers').textContent=customers.length;$('statVisits').textContent=visits.length;$('statMonth').textContent=visits.filter(v=>{const d=new Date(v.date+'T00:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).length}
function renderLists(){const recent=[...customers].sort((a,b)=>{const ad=(a.visits||[]).map(v=>v.date).sort().pop()||a.createdAt||'';const bd=(b.visits||[]).map(v=>v.date).sort().pop()||b.createdAt||'';return bd.localeCompare(ad)}).slice(0,4);$('recentList').innerHTML=recent.length?recent.map(card).join(''):'<div class="empty show"><span>♡</span><b>还没有顾客</b><p>点击上方添加第一位顾客。</p></div>';filterCustomers()}
function filterCustomers(){const q=$('searchInput').value.trim().toLowerCase();const list=customers.filter(c=>[c.name,c.phone,c.gender,c.features,c.tech,c.notes,c.tipPattern,...(c.visits||[]).flatMap(v=>[v.service,v.tech,v.notes])].join(' ').toLowerCase().includes(q));$('customerList').innerHTML=list.map(card).join('');$('customerList').classList.toggle('manage-mode',manage);$('recentList').classList.toggle('manage-mode',manage);$('emptyCustomers').classList.toggle('show',!list.length)}
function renderAll(){renderStats();renderLists();if(document.querySelector('#detail.active'))renderDetail()}
function resetForm(){$('customerForm').reset();$('customerId').value='';$('formTitle').textContent='添加新顾客';$('cancelEdit').classList.add('hidden')}
function editCustomer(id){const c=customers.find(x=>x.id===id);if(!c)return;$('customerId').value=c.id;$('name').value=c.name;$('phone').value=c.phone||'';$('gender').value=c.gender||'未填写';$('tech').value=c.tech||'';$('features').value=c.features||'';$('notes').value=c.notes||'';$('tipPattern').value=c.tipPattern||'';$('formTitle').textContent='编辑顾客资料';$('cancelEdit').classList.remove('hidden');go('add')}
function renderDetail(){const c=customers.find(x=>x.id===activeId);if(!c){go('customers');return}const visits=[...(c.visits||[])].sort((a,b)=>b.date.localeCompare(a.date));const spent=visits.reduce((s,v)=>s+(Number(v.amount)||0),0),tips=visits.reduce((s,v)=>s+(Number(v.tip)||0),0);$('detailBody').innerHTML=`<section class="profile"><span class="kicker">CUSTOMER PROFILE</span><h1>${esc(c.name)}</h1><a class="profile-phone" href="tel:${esc(c.phone||'')}">${esc(c.phone||'未填写电话号码')}</a><div class="info-grid"><div><span>来访次数</span><b>${visits.length} 次</b></div><div><span>常找技师</span><b>${esc(c.tech||'—')}</b></div><div><span>顾客特征</span><b>${esc(c.features||'—')}</b></div><div><span>小费情况</span><b>${esc(c.tipPattern||'—')}</b></div><div><span>累计消费</span><b>${money(spent)}</b></div><div><span>累计小费</span><b>${money(tips)}</b></div><div style="grid-column:1/-1"><span>注意事项</span><b>${esc(c.notes||'—')}</b></div></div><div class="profile-buttons"><button class="primary" id="addVisit">＋ 添加来访</button><button class="secondary" id="editProfile">编辑资料</button></div></section><section class="visits"><div class="visits-head"><div><span class="kicker">VISIT HISTORY</span><h2>来访记录</h2></div></div>${visits.length?visits.map(v=>`<article class="visit-item"><div class="visit-top"><b>${esc(v.service)}</b><time>${esc(v.date)}</time></div><div class="visit-meta">技师：${esc(v.tech||'未填写')}<br>消费：${money(v.amount)} · 小费：${money(v.tip)}${v.notes?`<br>备注：${esc(v.notes)}`:''}</div><button class="delete-visit" data-delete-visit="${v.id}">删除本次记录</button></article>`).join(''):'<div class="empty show"><span>♡</span><b>还没有来访记录</b><p>点击“添加来访”开始记录。</p></div>'}</section>`;$('addVisit').onclick=openVisit;$('editProfile').onclick=()=>editCustomer(c.id)}
function openVisit(){$('visitForm').reset();$('visitDate').value=new Date().toISOString().slice(0,10);$('visitDialog').showModal()}
function clickCard(e){const del=e.target.dataset.delete,edit=e.target.dataset.edit,view=e.target.closest('[data-view]')?.dataset.view;if(del){e.stopPropagation();if(confirm('确定删除这位顾客和全部来访记录吗？')){customers=customers.filter(c=>c.id!==del);save();toast('顾客已删除')}}else if(edit){e.stopPropagation();editCustomer(edit)}else if(view){activeId=view;go('detail')}}
$('customerForm').onsubmit=e=>{e.preventDefault();const id=$('customerId').value;const data={name:$('name').value.trim(),phone:$('phone').value.trim(),gender:$('gender').value,tech:$('tech').value.trim(),features:$('features').value.trim(),notes:$('notes').value.trim(),tipPattern:$('tipPattern').value.trim()};if(id){Object.assign(customers.find(c=>c.id===id),data);toast('顾客资料已更新')}else{customers.unshift({id:uid(),...data,createdAt:new Date().toISOString(),visits:[]});toast('顾客已保存')}save();resetForm();go('customers')};
$('visitForm').onsubmit=e=>{e.preventDefault();const c=customers.find(x=>x.id===activeId);if(!c)return;c.visits=c.visits||[];c.visits.push({id:uid(),date:$('visitDate').value,service:$('service').value.trim(),tech:$('visitTech').value.trim(),amount:$('amount').value,tip:$('tip').value,notes:$('visitNotes').value.trim()});save();$('visitDialog').close();renderDetail();toast('来访已保存，次数自动增加')};
$('detailBody').onclick=e=>{const id=e.target.dataset.deleteVisit;if(id&&confirm('确定删除这次来访吗？')){const c=customers.find(x=>x.id===activeId);c.visits=c.visits.filter(v=>v.id!==id);save();renderDetail();toast('来访记录已删除')}};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('menuBtn').onclick=openDrawer;$('closeDrawer').onclick=closeDrawer;$('shade').onclick=closeDrawer;$('searchInput').oninput=filterCustomers;$('customerList').onclick=clickCard;$('recentList').onclick=clickCard;$('manageBtn').onclick=()=>{manage=!manage;$('manageBtn').textContent=manage?'完成':'管理';renderLists();go('customers')};$('closeVisit').onclick=()=>$('visitDialog').close();renderAll();
